### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by JellyBubb1e** [KxmischesDomi/MushroomAdditionsWiki#1]
**Describe the bug**
Crash when creating a new world.

**Platform(s)**

- [x] Fabric
- [ ] Forge

<details>
<summary>mod list</summary>
<pre><code>
        - adorn 3.6.1+1.19
	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- adventurez 1.4.16
	- ambientenvironment 8.0+3
	- ambientsounds 5.2.5
	- appleskin 2.4.1+mc1.19
	- architectury 6.2.43
	- attributefix 17.1.3
	- autofish 0.9.5-SNAPSHOT
	- awesomedungeon 3.0.0
	- badpackets 0.2.0
	- bclib 2.1.0
	- betteradvancements 0.2.2.142
	- betteranimationscollection 4.0.1
	- betterbeds 1.2.0
	- betterend 2.1.0
	- betternether 7.1.0
	- blossom 1.0.5
	- blur 2.6.0
	- bobby 4.0.0
	- bookshelf 16.1.5
	- bosses_of_mass_destruction 1.4.2-1.19
	- bountiful 3.0.0
	- byg 2.0.0.11
	- capybara 1.0.6
	- cardinal-components 5.0.1
	- cardinal-components-base 5.0.1 via cardinal-components
	- cardinal-components-block 5.0.1 via cardinal-components
	- cardinal-components-chunk 5.0.1 via cardinal-components
	- cardinal-components-entity 5.0.1 via cardinal-components
	- cardinal-components-item 5.0.1 via cardinal-components
	- cardinal-components-level 5.0.1 via cardinal-components
	- cardinal-components-scoreboard 5.0.1 via cardinal-components
	- cardinal-components-world 5.0.1 via cardinal-components
	- cem 0.7.1
	- charm 4.2.2
	- citresewn 1.1.1+1.19
	- citresewn-defaults 1.1.1+1.19 via citresewn
	- cloth-api 4.0.65
	- cloth-basic-math 0.6.1 via cloth-api
	- cloth-client-events-v0 4.0.65 via cloth-api
	- cloth-common-events-v1 4.0.65 via cloth-api
	- cloth-config 8.2.88
	- cloth-scissors-api-v1 4.0.65 via cloth-api
	- cloth-utils-v1 4.0.65 via cloth-api
	- clumps 9.0.0+11
	- coat 1.0.0-beta.17+mc22w17a via completeconfig
	- colormatic 3.1.2+mc.1.19
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_typesafe_config 1.4.2 via bobby
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- completeconfig-gui-cloth 2.0.0 via completeconfig
	- completeconfig-gui-coat 2.0.0 via completeconfig
	- conditional-mixin 0.3.0 via cull-less-leaves
	- continuity 2.0.1+1.19
	- controlling 10.0+6
	- cosmetic-armor 1.4.0
	- crawl 0.11.2
	- creativecore 2.8.5
	- creeperoverhaul 2.0.3
	- cull-less-leaves 1.0.5
	- customportalapi 0.0.1-beta52-1.19 via deeperdarker
	- cutehermitcrabs 2.0.3-1.19.2
	- dawn 3.5.0
	- deeperdarker 1.0.2b-fabric
	- diagonalfences 4.2.1
	- dragonloot 1.1.2
	- dungeons_arise 2.1.51
	- dynamicfps 2.2.0
	- dynamicsoundfilters 1.3.0+1.19
	- earthtojavamobs 1.9.3
	- ecologics 2.1.9
	- edenring 0.6.4
	- effective 1.2.2
	- enchdesc 13.0.3
	- endgoblintraders 1.5.1
	- enhancedblockentities 0.7.1+1.19
	- enhancedcelestials 2.1.0.1
	- entity_texture_features 4.0.2
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- everycomp 1.19.2-2.0.4
	- expandeddelight 0.2.2
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
	- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
	- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
	- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fake-player-api 0.4.0 via the_bumblezone
	- fallingleaves 1.12.2+1.19.2
	- fallingtree 3.10.0
	- farmersdelight 1.19-1.3.3
	- farmersknives 2.1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- forgeconfigapiport 4.2.6
	- frame 0.26.1+1.19-fabric
	- frame-api-base 0.2.1+906ebc04a9 via frame
	- frame-blocks-v0 0.1.3+233e7428a9 via frame
	- frame-config-v0 0.3.1+0fa45150a9 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-enchantments-v0 0.1.0+4093105da9 via frame
	- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
	- frame-items-v0 0.1.3+906ebc04a9 via frame
	- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
	- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
	- frame-rendering-v0 0.1.5+906ebc04a9 via frame
	- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
	- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
	- frame-woods-v0 0.2.1+6a33fbada9 via frame
	- friendsandfoes 1.5.10
	- fwaystones 3.0.3+mc1.19.2
	- galosphere 1.19.1-1.1.2
	- geckolib3 3.1.18
	- geodes 1.5.1
	- go-fish 1.6.0-1.19.1
	- goblintraders 1.5.2
	- goodall 1.1.1
	- guardvillagers 1.19-1.0.16
	- hedgehog 1.19-1.0.0
	- illuminations 1.10.8
	- imblocker 1.0.19
	- indium 1.0.9+mc1.19.2
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.3.1
	- itemmodelfix 1.0.3+1.19
	- jade 8.2.1
	- java 17
	- kambrik 4.0-1.19.2
	- krypton 0.2.1
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- libraryferret 3.0.0
	- litematica 0.12.4
	- lithium 0.8.3
	- lovely_snails 1.1.0+1.19
	- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
	- malilib 0.13.0
	- mcwfences 1.0.6
	- memoryleakfix 1.19.1-0.7.0
	- midnightlib 0.6.0 via the_bumblezone
	- minecraft 1.19.2
	- mm 2.3 via crawl
	- mobscarecrow 2.2.1-1.19.1
	- modmenu 4.0.6
	- moonlight 1.19.2-2.0.28
	- more_babies 0.5.4
	- mousetweaks 2.22
	- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
	- mushroom_additions 1.0.0
	- mvs 2.5.8
	- namepain 1.4.0
	- naturalist 2.1.1
	- naturescompass 1.19.2-2.0.4-fabric
	- nears 1.2.3
	- nochatreports 1.19.2-v1.11.2
	- notenoughanimations 1.6.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- org_yaml_snakeyaml 1.31 via viafabric
	- paintings 10.2.1.0
	- patchouli 1.19.2-76-FABRIC
	- pickupnotifier 4.2.0
	- pinlib 0.1.3+1.19 via fwaystones
	- polymorph 0.45.0+1.19.2
	- pride 1.1.2+1.19 via lambdynlights
	- promenade 2.7.1
	- puzzle 1.4.0-1.19
	- puzzle-base 1.4.0-1.19 via puzzle
	- puzzle-gui 1.4.0-1.19 via puzzle
	- puzzle-models 1.4.0-1.19 via puzzle
	- puzzle-splashscreen 1.4.0-1.19 via puzzle
	- puzzleslib 4.3.1
	- raised 1.1.2
	- repurposed_structures 6.1.1+1.19
	- roughlyenoughitems 9.1.537
	- roughlyenoughresources 2.6.0
	- satin 1.8.0 via blur
	- skinlayers 1.5.1-mc1.19.1
	- skyvillages 1.0.2.1
	- snowyspirit 1.19.2-2.0.2
	- sodium 0.4.4+build.18
	- spark 1.9.36
	- spirit 2.1.12
	- spruceui 4.0.0+1.19 via enhancedblockentities
	- starlight 1.1.1+fabric.ae22326
	- stoneholm 1.4.4
	- supplementaries 1.19.2-2.1.3
	- t_and_t 1.8.2
	- terrablender 2.0.1.127
	- terraform-shapes-api-v1 4.0.0 via promenade
	- the_bumblezone 6.1.9+1.19.2
	- thonkutil 2.15.4+1.19
	- thonkutil-base 1.13.2+4a8c408a57 via thonkutil
	- thonkutil-capes-v1 1.4.2+3eb2749857 via thonkutil
	- thonkutil-coords-v1 1.1.2+8ff533c957 via thonkutil
	- thonkutil-customization-v1 1.1.2+8ff533c957 via thonkutil
	- thonkutil-legacy 1.1.2+5d4263f557 via thonkutil
	- thonkutil-modchecker-v1 1.1.3+bd4b387957 via thonkutil
	- thonkutil-potions-v0 1.5.2+8ff533c957 via thonkutil
	- thonkutil-titlescreen-v1 1.2.2+8ff533c957 via thonkutil
	- thonkutil-trades-v1 1.2.2+8ff533c957 via thonkutil
	- tooltiprareness 1.0.6
	- tooltipsplus 1.2.3-beta+1.19
	- travelersbackpack 1.19.2-8.2.1
	- trinkets 3.4.0
	- tumbleweed 0.5.1
	- tweakeroo 0.14.3
	- twigs 2.0.0-beta.9+1.19-fabric
	- untitledduckmod 0.6.1
	- vanilla_degus 1.3.2
	- viafabric 0.4.9+19-main
	- viafabric-mc119 0.4.9+19-main via viafabric
	- viaversion 4.4.3-SNAPSHOT via viafabric
	- voidz 1.0.9
	- waterdripsound 1.19-0.3.0
	- windchimes 1.2.1
	- wondrouswilds 1.19-1.0.1
	- worldedit 7.2.12+6240-87f4ae1
	- wwoo 3.1.7
	- xaerominimap 22.14.1
	- xaeroworldmap 1.27.0
</code></pre>
</details>

**Environment(s)**

- [x] Singleplayer
- [ ] Server

**log(s)**
[2022-09-12-2.log](https://github.com/KxmischesDomi/MushroomAdditions/files/9548680/2022-09-12-2.log)

Thx !

**Comment by DomiIRL** [comment]
Seems to be an issue with [byg](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric).
Haven't seen that error ever but that modid is in the stacktrace with the biome "lush_stacks". I don't know whats exactly happening there but looks like biomes conflicting or smth

**Comment by DomiIRL** [comment]
This issue seems to be happening with other mods too as I can read in the issues of the byg mod.
So I'll close this issue and they'll have to fix it.
